# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _adf4377
else:
    import _adf4377

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


NO_OS_SPI_CPHA = _adf4377.NO_OS_SPI_CPHA
NO_OS_SPI_CPOL = _adf4377.NO_OS_SPI_CPOL
SPI_MAX_BUS_NUMBER = _adf4377.SPI_MAX_BUS_NUMBER
NO_OS_SPI_MODE_0 = _adf4377.NO_OS_SPI_MODE_0
NO_OS_SPI_MODE_1 = _adf4377.NO_OS_SPI_MODE_1
NO_OS_SPI_MODE_2 = _adf4377.NO_OS_SPI_MODE_2
NO_OS_SPI_MODE_3 = _adf4377.NO_OS_SPI_MODE_3
NO_OS_SPI_BIT_ORDER_MSB_FIRST = _adf4377.NO_OS_SPI_BIT_ORDER_MSB_FIRST
NO_OS_SPI_BIT_ORDER_LSB_FIRST = _adf4377.NO_OS_SPI_BIT_ORDER_LSB_FIRST
NO_OS_SPI_SINGLE_LANE = _adf4377.NO_OS_SPI_SINGLE_LANE
NO_OS_SPI_DUAL_LANE = _adf4377.NO_OS_SPI_DUAL_LANE
NO_OS_SPI_QUAD_LANE = _adf4377.NO_OS_SPI_QUAD_LANE
NO_OS_SPI_OCTO_LANE = _adf4377.NO_OS_SPI_OCTO_LANE
class no_os_spi_msg(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    tx_buff = property(_adf4377.no_os_spi_msg_tx_buff_get, _adf4377.no_os_spi_msg_tx_buff_set)
    rx_buff = property(_adf4377.no_os_spi_msg_rx_buff_get, _adf4377.no_os_spi_msg_rx_buff_set)
    bytes_number = property(_adf4377.no_os_spi_msg_bytes_number_get, _adf4377.no_os_spi_msg_bytes_number_set)
    cs_change = property(_adf4377.no_os_spi_msg_cs_change_get, _adf4377.no_os_spi_msg_cs_change_set)
    cs_change_delay = property(_adf4377.no_os_spi_msg_cs_change_delay_get, _adf4377.no_os_spi_msg_cs_change_delay_set)
    cs_delay_first = property(_adf4377.no_os_spi_msg_cs_delay_first_get, _adf4377.no_os_spi_msg_cs_delay_first_set)
    cs_delay_last = property(_adf4377.no_os_spi_msg_cs_delay_last_get, _adf4377.no_os_spi_msg_cs_delay_last_set)

    def __init__(self):
        _adf4377.no_os_spi_msg_swiginit(self, _adf4377.new_no_os_spi_msg())
    __swig_destroy__ = _adf4377.delete_no_os_spi_msg

# Register no_os_spi_msg in _adf4377:
_adf4377.no_os_spi_msg_swigregister(no_os_spi_msg)
class no_os_platform_spi_delays(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cs_delay_first = property(_adf4377.no_os_platform_spi_delays_cs_delay_first_get, _adf4377.no_os_platform_spi_delays_cs_delay_first_set)
    cs_delay_last = property(_adf4377.no_os_platform_spi_delays_cs_delay_last_get, _adf4377.no_os_platform_spi_delays_cs_delay_last_set)

    def __init__(self):
        _adf4377.no_os_platform_spi_delays_swiginit(self, _adf4377.new_no_os_platform_spi_delays())
    __swig_destroy__ = _adf4377.delete_no_os_platform_spi_delays

# Register no_os_platform_spi_delays in _adf4377:
_adf4377.no_os_platform_spi_delays_swigregister(no_os_platform_spi_delays)
class no_os_spi_init_param(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    device_id = property(_adf4377.no_os_spi_init_param_device_id_get, _adf4377.no_os_spi_init_param_device_id_set)
    max_speed_hz = property(_adf4377.no_os_spi_init_param_max_speed_hz_get, _adf4377.no_os_spi_init_param_max_speed_hz_set)
    chip_select = property(_adf4377.no_os_spi_init_param_chip_select_get, _adf4377.no_os_spi_init_param_chip_select_set)
    mode = property(_adf4377.no_os_spi_init_param_mode_get, _adf4377.no_os_spi_init_param_mode_set)
    bit_order = property(_adf4377.no_os_spi_init_param_bit_order_get, _adf4377.no_os_spi_init_param_bit_order_set)
    lanes = property(_adf4377.no_os_spi_init_param_lanes_get, _adf4377.no_os_spi_init_param_lanes_set)
    platform_ops = property(_adf4377.no_os_spi_init_param_platform_ops_get, _adf4377.no_os_spi_init_param_platform_ops_set)
    platform_delays = property(_adf4377.no_os_spi_init_param_platform_delays_get, _adf4377.no_os_spi_init_param_platform_delays_set)
    extra = property(_adf4377.no_os_spi_init_param_extra_get, _adf4377.no_os_spi_init_param_extra_set)
    parent = property(_adf4377.no_os_spi_init_param_parent_get, _adf4377.no_os_spi_init_param_parent_set)

    def __init__(self):
        _adf4377.no_os_spi_init_param_swiginit(self, _adf4377.new_no_os_spi_init_param())
    __swig_destroy__ = _adf4377.delete_no_os_spi_init_param

# Register no_os_spi_init_param in _adf4377:
_adf4377.no_os_spi_init_param_swigregister(no_os_spi_init_param)
class no_os_spibus_desc(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    mutex = property(_adf4377.no_os_spibus_desc_mutex_get, _adf4377.no_os_spibus_desc_mutex_set)
    slave_number = property(_adf4377.no_os_spibus_desc_slave_number_get, _adf4377.no_os_spibus_desc_slave_number_set)
    device_id = property(_adf4377.no_os_spibus_desc_device_id_get, _adf4377.no_os_spibus_desc_device_id_set)
    max_speed_hz = property(_adf4377.no_os_spibus_desc_max_speed_hz_get, _adf4377.no_os_spibus_desc_max_speed_hz_set)
    mode = property(_adf4377.no_os_spibus_desc_mode_get, _adf4377.no_os_spibus_desc_mode_set)
    bit_order = property(_adf4377.no_os_spibus_desc_bit_order_get, _adf4377.no_os_spibus_desc_bit_order_set)
    lanes = property(_adf4377.no_os_spibus_desc_lanes_get, _adf4377.no_os_spibus_desc_lanes_set)
    platform_ops = property(_adf4377.no_os_spibus_desc_platform_ops_get, _adf4377.no_os_spibus_desc_platform_ops_set)
    extra = property(_adf4377.no_os_spibus_desc_extra_get, _adf4377.no_os_spibus_desc_extra_set)

    def __init__(self):
        _adf4377.no_os_spibus_desc_swiginit(self, _adf4377.new_no_os_spibus_desc())
    __swig_destroy__ = _adf4377.delete_no_os_spibus_desc

# Register no_os_spibus_desc in _adf4377:
_adf4377.no_os_spibus_desc_swigregister(no_os_spibus_desc)
class no_os_spi_desc(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    bus = property(_adf4377.no_os_spi_desc_bus_get, _adf4377.no_os_spi_desc_bus_set)
    device_id = property(_adf4377.no_os_spi_desc_device_id_get, _adf4377.no_os_spi_desc_device_id_set)
    max_speed_hz = property(_adf4377.no_os_spi_desc_max_speed_hz_get, _adf4377.no_os_spi_desc_max_speed_hz_set)
    chip_select = property(_adf4377.no_os_spi_desc_chip_select_get, _adf4377.no_os_spi_desc_chip_select_set)
    mode = property(_adf4377.no_os_spi_desc_mode_get, _adf4377.no_os_spi_desc_mode_set)
    bit_order = property(_adf4377.no_os_spi_desc_bit_order_get, _adf4377.no_os_spi_desc_bit_order_set)
    lanes = property(_adf4377.no_os_spi_desc_lanes_get, _adf4377.no_os_spi_desc_lanes_set)
    platform_ops = property(_adf4377.no_os_spi_desc_platform_ops_get, _adf4377.no_os_spi_desc_platform_ops_set)
    platform_delays = property(_adf4377.no_os_spi_desc_platform_delays_get, _adf4377.no_os_spi_desc_platform_delays_set)
    extra = property(_adf4377.no_os_spi_desc_extra_get, _adf4377.no_os_spi_desc_extra_set)
    parent = property(_adf4377.no_os_spi_desc_parent_get, _adf4377.no_os_spi_desc_parent_set)

    def __init__(self):
        _adf4377.no_os_spi_desc_swiginit(self, _adf4377.new_no_os_spi_desc())
    __swig_destroy__ = _adf4377.delete_no_os_spi_desc

# Register no_os_spi_desc in _adf4377:
_adf4377.no_os_spi_desc_swigregister(no_os_spi_desc)
class no_os_spi_platform_ops(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    init = property(_adf4377.no_os_spi_platform_ops_init_get, _adf4377.no_os_spi_platform_ops_init_set)
    write_and_read = property(_adf4377.no_os_spi_platform_ops_write_and_read_get, _adf4377.no_os_spi_platform_ops_write_and_read_set)
    transfer = property(_adf4377.no_os_spi_platform_ops_transfer_get, _adf4377.no_os_spi_platform_ops_transfer_set)
    transfer_dma = property(_adf4377.no_os_spi_platform_ops_transfer_dma_get, _adf4377.no_os_spi_platform_ops_transfer_dma_set)
    transfer_dma_async = property(_adf4377.no_os_spi_platform_ops_transfer_dma_async_get, _adf4377.no_os_spi_platform_ops_transfer_dma_async_set)
    remove = property(_adf4377.no_os_spi_platform_ops_remove_get, _adf4377.no_os_spi_platform_ops_remove_set)
    transfer_abort = property(_adf4377.no_os_spi_platform_ops_transfer_abort_get, _adf4377.no_os_spi_platform_ops_transfer_abort_set)

    def __init__(self):
        _adf4377.no_os_spi_platform_ops_swiginit(self, _adf4377.new_no_os_spi_platform_ops())
    __swig_destroy__ = _adf4377.delete_no_os_spi_platform_ops

# Register no_os_spi_platform_ops in _adf4377:
_adf4377.no_os_spi_platform_ops_swigregister(no_os_spi_platform_ops)

def no_os_spi_init(desc, param):
    return _adf4377.no_os_spi_init(desc, param)

def no_os_spi_remove(desc):
    return _adf4377.no_os_spi_remove(desc)

def no_os_spi_write_and_read(desc, bytes_number):
    return _adf4377.no_os_spi_write_and_read(desc, bytes_number)

def no_os_spi_transfer(desc, msgs, len):
    return _adf4377.no_os_spi_transfer(desc, msgs, len)

def no_os_spi_transfer_dma(desc, msgs, len):
    return _adf4377.no_os_spi_transfer_dma(desc, msgs, len)

def no_os_spi_transfer_dma_async(desc, msgs, len, callback, ctx):
    return _adf4377.no_os_spi_transfer_dma_async(desc, msgs, len, callback, ctx)

def no_os_spi_transfer_abort(desc):
    return _adf4377.no_os_spi_transfer_abort(desc)

def no_os_spibus_init(param):
    return _adf4377.no_os_spibus_init(param)

def no_os_spibus_remove(bus_number):
    return _adf4377.no_os_spibus_remove(bus_number)
class linux_spi_init_param(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    device_id = property(_adf4377.linux_spi_init_param_device_id_get, _adf4377.linux_spi_init_param_device_id_set)
    chip_select = property(_adf4377.linux_spi_init_param_chip_select_get, _adf4377.linux_spi_init_param_chip_select_set)
    max_speed_hz = property(_adf4377.linux_spi_init_param_max_speed_hz_get, _adf4377.linux_spi_init_param_max_speed_hz_set)
    mode = property(_adf4377.linux_spi_init_param_mode_get, _adf4377.linux_spi_init_param_mode_set)

    def __init__(self):
        _adf4377.linux_spi_init_param_swiginit(self, _adf4377.new_linux_spi_init_param())
    __swig_destroy__ = _adf4377.delete_linux_spi_init_param

# Register linux_spi_init_param in _adf4377:
_adf4377.linux_spi_init_param_swigregister(linux_spi_init_param)
ADF4377_RESET_CMD = _adf4377.ADF4377_RESET_CMD
ADF4377_SDO_ACTIVE_SPI_3W = _adf4377.ADF4377_SDO_ACTIVE_SPI_3W
ADF4377_SDO_ACTIVE_SPI_4W = _adf4377.ADF4377_SDO_ACTIVE_SPI_4W
ADF4377_ADDR_ASC_AUTO_DECR = _adf4377.ADF4377_ADDR_ASC_AUTO_DECR
ADF4377_ADDR_ASC_AUTO_INCR = _adf4377.ADF4377_ADDR_ASC_AUTO_INCR
ADF4377_LSB_FIRST_MSB = _adf4377.ADF4377_LSB_FIRST_MSB
ADF4377_LSB_FIRST_LSB = _adf4377.ADF4377_LSB_FIRST_LSB
ADF4377_SOFT_RESET_N_OP = _adf4377.ADF4377_SOFT_RESET_N_OP
ADF4377_SOFT_RESET_EN = _adf4377.ADF4377_SOFT_RESET_EN
ADF4377_SPI_STREAM_EN = _adf4377.ADF4377_SPI_STREAM_EN
ADF4377_SPI_STREAM_DIS = _adf4377.ADF4377_SPI_STREAM_DIS
ADF4377_RB_SLAVE_REG = _adf4377.ADF4377_RB_SLAVE_REG
ADF4377_RB_MASTER_REG = _adf4377.ADF4377_RB_MASTER_REG
ADF4377_CHIP_TYPE = _adf4377.ADF4377_CHIP_TYPE
ADF4377_PRODUCT_ID_LSB = _adf4377.ADF4377_PRODUCT_ID_LSB
ADF4377_PRODUCT_ID_MSB = _adf4377.ADF4377_PRODUCT_ID_MSB
ADF4377_SPI_REVISION = _adf4377.ADF4377_SPI_REVISION
ADF4377_VENDOR_ID_LSB = _adf4377.ADF4377_VENDOR_ID_LSB
ADF4377_VENDOR_ID_MSB = _adf4377.ADF4377_VENDOR_ID_MSB
ADF4377_R00F_RSV1 = _adf4377.ADF4377_R00F_RSV1
ADF4377_VCO_CALIB_DIS = _adf4377.ADF4377_VCO_CALIB_DIS
ADF4377_VCO_CALIB_EN = _adf4377.ADF4377_VCO_CALIB_EN
ADF4377_REF_DBLR_DIS = _adf4377.ADF4377_REF_DBLR_DIS
ADF4377_REF_DBLR_EN = _adf4377.ADF4377_REF_DBLR_EN
ADF4377_DCLK_DIV2_1 = _adf4377.ADF4377_DCLK_DIV2_1
ADF4377_DCLK_DIV2_2 = _adf4377.ADF4377_DCLK_DIV2_2
ADF4377_DCLK_DIV2_4 = _adf4377.ADF4377_DCLK_DIV2_4
ADF4377_DCLK_DIV2_8 = _adf4377.ADF4377_DCLK_DIV2_8
ADF4377_CLKOUT_DIV_1 = _adf4377.ADF4377_CLKOUT_DIV_1
ADF4377_CLKOUT_DIV_2 = _adf4377.ADF4377_CLKOUT_DIV_2
ADF4377_CLKOUT_DIV_4 = _adf4377.ADF4377_CLKOUT_DIV_4
ADF4377_CLKOUT_DIV_8 = _adf4377.ADF4377_CLKOUT_DIV_8
ADF4377_MIN_R_DIV = _adf4377.ADF4377_MIN_R_DIV
ADF4378_MAX_R_DIV = _adf4377.ADF4378_MAX_R_DIV
ADF4377_M_VCO_0 = _adf4377.ADF4377_M_VCO_0
ADF4377_M_VCO_1 = _adf4377.ADF4377_M_VCO_1
ADF4377_M_VCO_2 = _adf4377.ADF4377_M_VCO_2
ADF4377_M_VCO_3 = _adf4377.ADF4377_M_VCO_3
M_VCO_BIAS_MIN = _adf4377.M_VCO_BIAS_MIN
M_VCO_BIAS_MAX = _adf4377.M_VCO_BIAS_MAX
ADF4377_VCO_BAND_MIN = _adf4377.ADF4377_VCO_BAND_MIN
ADF4377_VCO_BAND_MAX = _adf4377.ADF4377_VCO_BAND_MAX
ADF4377_CURRENT_SINK = _adf4377.ADF4377_CURRENT_SINK
ADF4377_CURRENT_SOURCE = _adf4377.ADF4377_CURRENT_SOURCE
ADF4377_CP_0MA7 = _adf4377.ADF4377_CP_0MA7
ADF4377_CP_0MA9 = _adf4377.ADF4377_CP_0MA9
ADF4377_CP_1MA1 = _adf4377.ADF4377_CP_1MA1
ADF4377_CP_1MA3 = _adf4377.ADF4377_CP_1MA3
ADF4377_CP_1MA4 = _adf4377.ADF4377_CP_1MA4
ADF4377_CP_1MA8 = _adf4377.ADF4377_CP_1MA8
ADF4377_CP_2MA2 = _adf4377.ADF4377_CP_2MA2
ADF4377_CP_2MA5 = _adf4377.ADF4377_CP_2MA5
ADF4377_CP_2MA9 = _adf4377.ADF4377_CP_2MA9
ADF4377_CP_3MA6 = _adf4377.ADF4377_CP_3MA6
ADF4377_CP_4MA3 = _adf4377.ADF4377_CP_4MA3
ADF4377_CP_5MA0 = _adf4377.ADF4377_CP_5MA0
ADF4377_CP_5MA7 = _adf4377.ADF4377_CP_5MA7
ADF4377_CP_7MA2 = _adf4377.ADF4377_CP_7MA2
ADF4377_CP_8MA6 = _adf4377.ADF4377_CP_8MA6
ADF4377_CP_10MA1 = _adf4377.ADF4377_CP_10MA1
ADF4377_1V8_LOGIC = _adf4377.ADF4377_1V8_LOGIC
ADF4377_3V3_LOGIC = _adf4377.ADF4377_3V3_LOGIC
ADF4377_R_N_DEL_MIN = _adf4377.ADF4377_R_N_DEL_MIN
ADF4377_R_N_DEL_MAX = _adf4377.ADF4377_R_N_DEL_MAX
ADF4377_CLKOUT_320MV = _adf4377.ADF4377_CLKOUT_320MV
ADF4377_CLKOUT_420MV = _adf4377.ADF4377_CLKOUT_420MV
ADF4377_CLKOUT_530MV = _adf4377.ADF4377_CLKOUT_530MV
ADF4377_CLKOUT_640MV = _adf4377.ADF4377_CLKOUT_640MV
ADF4377_PD_CLK_N_OP = _adf4377.ADF4377_PD_CLK_N_OP
ADF4377_PD_CLK_PD = _adf4377.ADF4377_PD_CLK_PD
ADF4377_PD_RDET_N_OP = _adf4377.ADF4377_PD_RDET_N_OP
ADF4377_PD_RDET_PD = _adf4377.ADF4377_PD_RDET_PD
ADF4377_PD_ADC_N_OP = _adf4377.ADF4377_PD_ADC_N_OP
ADF4377_PD_ADC_PD = _adf4377.ADF4377_PD_ADC_PD
ADF4377_PD_CALADC_N_OP = _adf4377.ADF4377_PD_CALADC_N_OP
ADF4377_PD_CALADC_PD = _adf4377.ADF4377_PD_CALADC_PD
ADF4377_PD_ALL_N_OP = _adf4377.ADF4377_PD_ALL_N_OP
ADF4377_PD_ALL_PD = _adf4377.ADF4377_PD_ALL_PD
ADF4377_PD_RDIV_N_OP = _adf4377.ADF4377_PD_RDIV_N_OP
ADF4377_PD_RDIV_PD = _adf4377.ADF4377_PD_RDIV_PD
ADF4377_PD_NDIV_N_OP = _adf4377.ADF4377_PD_NDIV_N_OP
ADF4377_PD_NDIV_PD = _adf4377.ADF4377_PD_NDIV_PD
ADF4377_PD_VCO_N_OP = _adf4377.ADF4377_PD_VCO_N_OP
ADF4377_PD_VCO_PD = _adf4377.ADF4377_PD_VCO_PD
ADF4377_PD_LD_N_OP = _adf4377.ADF4377_PD_LD_N_OP
ADF4377_PD_LD_PD = _adf4377.ADF4377_PD_LD_PD
ADF4377_PD_PFDCP_N_OP = _adf4377.ADF4377_PD_PFDCP_N_OP
ADF4377_PD_PFDCP_PD = _adf4377.ADF4377_PD_PFDCP_PD
ADF4377_PD_CLKOUT1_N_OP = _adf4377.ADF4377_PD_CLKOUT1_N_OP
ADF4377_PD_CLKOUT1_PD = _adf4377.ADF4377_PD_CLKOUT1_PD
ADF4377_PD_CLKOUT2_N_OP = _adf4377.ADF4377_PD_CLKOUT2_N_OP
ADF4377_PD_CLKOUT2_PD = _adf4377.ADF4377_PD_CLKOUT2_PD
ADF4377_LDWIN_PW_NARROW = _adf4377.ADF4377_LDWIN_PW_NARROW
ADF4377_LDWIN_PW_WIDE = _adf4377.ADF4377_LDWIN_PW_WIDE
ADF4377_EN_DNCLK_OFF = _adf4377.ADF4377_EN_DNCLK_OFF
ADF4377_EN_DNCLK_ON = _adf4377.ADF4377_EN_DNCLK_ON
ADF4377_EN_DRCLK_OFF = _adf4377.ADF4377_EN_DRCLK_OFF
ADF4377_EN_DRCLK_ON = _adf4377.ADF4377_EN_DRCLK_ON
ADF4377_RST_LD_INACTIVE = _adf4377.ADF4377_RST_LD_INACTIVE
ADF4377_RST_LD_ACTIVE = _adf4377.ADF4377_RST_LD_ACTIVE
ADF4377_MUXOUT_HIGH_Z = _adf4377.ADF4377_MUXOUT_HIGH_Z
ADF4377_MUXOUT_LKDET = _adf4377.ADF4377_MUXOUT_LKDET
ADF4377_MUXOUT_LOW = _adf4377.ADF4377_MUXOUT_LOW
ADF4377_MUXOUT_DIV_RCLK_2 = _adf4377.ADF4377_MUXOUT_DIV_RCLK_2
ADF4377_MUXOUT_DIV_NCLK_2 = _adf4377.ADF4377_MUXOUT_DIV_NCLK_2
ADF4377_MUXOUT_HIGH = _adf4377.ADF4377_MUXOUT_HIGH
ADF4377_EN_CPTEST_OFF = _adf4377.ADF4377_EN_CPTEST_OFF
ADF4377_EN_CPTEST_ON = _adf4377.ADF4377_EN_CPTEST_ON
ADF4377_CP_DOWN_OFF = _adf4377.ADF4377_CP_DOWN_OFF
ADF4377_CP_DOWN_ON = _adf4377.ADF4377_CP_DOWN_ON
ADF4377_CP_UP_OFF = _adf4377.ADF4377_CP_UP_OFF
ADF4377_CP_UP_ON = _adf4377.ADF4377_CP_UP_ON
ADF4377_BST_LARGE_REF_IN = _adf4377.ADF4377_BST_LARGE_REF_IN
ADF4377_BST_SMALL_REF_IN = _adf4377.ADF4377_BST_SMALL_REF_IN
ADF4377_FILT_REF_OFF = _adf4377.ADF4377_FILT_REF_OFF
ADF4377_FILT_REF_ON = _adf4377.ADF4377_FILT_REF_ON
ADF4377_REF_SEL_DMA = _adf4377.ADF4377_REF_SEL_DMA
ADF4377_REF_SEL_LNA = _adf4377.ADF4377_REF_SEL_LNA
ADF4377_RST_SYS_INACTIVE = _adf4377.ADF4377_RST_SYS_INACTIVE
ADF4377_RST_SYS_ACTIVE = _adf4377.ADF4377_RST_SYS_ACTIVE
ADF4377_R021_RSV1 = _adf4377.ADF4377_R021_RSV1
ADF4377_R022_RSV1 = _adf4377.ADF4377_R022_RSV1
ADF4377_R023_RSV1 = _adf4377.ADF4377_R023_RSV1
ADF4377_VCO_BAND_DIV_MIN = _adf4377.ADF4377_VCO_BAND_DIV_MIN
ADF4377_VCO_BAND_DIV_MAX = _adf4377.ADF4377_VCO_BAND_DIV_MAX
ADF4377_R02C_RSV1 = _adf4377.ADF4377_R02C_RSV1
ADF4377_ADC_A_CONV_ADC_ST_CNV = _adf4377.ADF4377_ADC_A_CONV_ADC_ST_CNV
ADF4377_ADC_A_CONV_VCO_CALIB = _adf4377.ADF4377_ADC_A_CONV_VCO_CALIB
ADF4377_DCLK_DIV1_1 = _adf4377.ADF4377_DCLK_DIV1_1
ADF4377_DCLK_DIV1_2 = _adf4377.ADF4377_DCLK_DIV1_2
ADF4377_DCLK_DIV1_8 = _adf4377.ADF4377_DCLK_DIV1_8
ADF4377_DCLK_DIV1_32 = _adf4377.ADF4377_DCLK_DIV1_32
ADF4377_R031_RSV1 = _adf4377.ADF4377_R031_RSV1
ADF4377_ADC_CLK_SEL_N_OP = _adf4377.ADF4377_ADC_CLK_SEL_N_OP
ADF4377_ADC_CLK_SEL_SPI_CLK = _adf4377.ADF4377_ADC_CLK_SEL_SPI_CLK
ADF4377_R033_RSV1 = _adf4377.ADF4377_R033_RSV1
ADF4377_R034_RSV1 = _adf4377.ADF4377_R034_RSV1
ADF4377_R03A_RSV1 = _adf4377.ADF4377_R03A_RSV1
ADF4377_R03B_RSV1 = _adf4377.ADF4377_R03B_RSV1
ADF4377_O_VCO_BAND_VCO_CALIB = _adf4377.ADF4377_O_VCO_BAND_VCO_CALIB
ADF4377_O_VCO_BAND_M_VCO = _adf4377.ADF4377_O_VCO_BAND_M_VCO
ADF4377_O_VCO_CORE_VCO_CALIB = _adf4377.ADF4377_O_VCO_CORE_VCO_CALIB
ADF4377_O_VCO_CORE_M_VCO = _adf4377.ADF4377_O_VCO_CORE_M_VCO
ADF4377_O_VCO_BIAS_VCO_CALIB = _adf4377.ADF4377_O_VCO_BIAS_VCO_CALIB
ADF4377_O_VCO_BIAS_M_VCO = _adf4377.ADF4377_O_VCO_BIAS_M_VCO
ADF4377_R042_RSV1 = _adf4377.ADF4377_R042_RSV1
ADF4377_SPI_WRITE_CMD = _adf4377.ADF4377_SPI_WRITE_CMD
ADF4377_BUFF_SIZE_BYTES = _adf4377.ADF4377_BUFF_SIZE_BYTES
ADF4377_MAX_VCO_FREQ = _adf4377.ADF4377_MAX_VCO_FREQ
ADF4377_MIN_VCO_FREQ = _adf4377.ADF4377_MIN_VCO_FREQ
ADF4377_MAX_REFIN_FREQ = _adf4377.ADF4377_MAX_REFIN_FREQ
ADF4377_MIN_REFIN_FREQ = _adf4377.ADF4377_MIN_REFIN_FREQ
ADF4377_MAX_FREQ_PFD = _adf4377.ADF4377_MAX_FREQ_PFD
ADF4377_MIN_FREQ_PFD = _adf4377.ADF4377_MIN_FREQ_PFD
ADF4377_MAX_CLKPN_FREQ = _adf4377.ADF4377_MAX_CLKPN_FREQ
ADF4377_MIN_CLKPN_FREQ = _adf4377.ADF4377_MIN_CLKPN_FREQ
ADF4377_FREQ_PFD_80MHZ = _adf4377.ADF4377_FREQ_PFD_80MHZ
ADF4377_FREQ_PFD_125MHZ = _adf4377.ADF4377_FREQ_PFD_125MHZ
ADF4377_FREQ_PFD_160MHZ = _adf4377.ADF4377_FREQ_PFD_160MHZ
ADF4377_FREQ_PFD_250MHZ = _adf4377.ADF4377_FREQ_PFD_250MHZ
ADF4377_FREQ_PFD_320MHZ = _adf4377.ADF4377_FREQ_PFD_320MHZ
ADF4377_CPI_VAL_MAX = _adf4377.ADF4377_CPI_VAL_MAX
ADF4377_RFOUT_MAX = _adf4377.ADF4377_RFOUT_MAX
ADF4377_RFOUT_MIN = _adf4377.ADF4377_RFOUT_MIN
ADF4377_CLKOUT_DIV_REG_VAL_MAX = _adf4377.ADF4377_CLKOUT_DIV_REG_VAL_MAX
ADF4377_LKD_DELAY_US = _adf4377.ADF4377_LKD_DELAY_US
ADF4377_POR_DELAY_US = _adf4377.ADF4377_POR_DELAY_US
ADF4377_BLEED_WORD_MAX = _adf4377.ADF4377_BLEED_WORD_MAX
ADF4377_REF_DIV_MAX = _adf4377.ADF4377_REF_DIV_MAX
ADF4377_OUT_PWR_MAX = _adf4377.ADF4377_OUT_PWR_MAX
ADF4377_CLKIN_REF_MIN = _adf4377.ADF4377_CLKIN_REF_MIN
ADF4377_CLKIN_REF_MAX = _adf4377.ADF4377_CLKIN_REF_MAX
ADF4377_SR_DEL_MAX = _adf4377.ADF4377_SR_DEL_MAX
ADF4377_SR_MON_DELAY_US = _adf4377.ADF4377_SR_MON_DELAY_US
ADF4377_SPI_SCRATCHPAD_TEST_A = _adf4377.ADF4377_SPI_SCRATCHPAD_TEST_A
ADF4377_SPI_SCRATCHPAD_TEST_B = _adf4377.ADF4377_SPI_SCRATCHPAD_TEST_B
ADF4377_SPI_DUMMY_DATA = _adf4377.ADF4377_SPI_DUMMY_DATA
ADF4377 = _adf4377.ADF4377
ADF4378 = _adf4377.ADF4378
class adf4377_init_param(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    spi_init = property(_adf4377.adf4377_init_param_spi_init_get, _adf4377.adf4377_init_param_spi_init_set)
    gpio_ce_param = property(_adf4377.adf4377_init_param_gpio_ce_param_get, _adf4377.adf4377_init_param_gpio_ce_param_set)
    gpio_enclk1_param = property(_adf4377.adf4377_init_param_gpio_enclk1_param_get, _adf4377.adf4377_init_param_gpio_enclk1_param_set)
    gpio_enclk2_param = property(_adf4377.adf4377_init_param_gpio_enclk2_param_get, _adf4377.adf4377_init_param_gpio_enclk2_param_set)
    dev_id = property(_adf4377.adf4377_init_param_dev_id_get, _adf4377.adf4377_init_param_dev_id_set)
    spi4wire = property(_adf4377.adf4377_init_param_spi4wire_get, _adf4377.adf4377_init_param_spi4wire_set)
    clkin_freq = property(_adf4377.adf4377_init_param_clkin_freq_get, _adf4377.adf4377_init_param_clkin_freq_set)
    f_clk = property(_adf4377.adf4377_init_param_f_clk_get, _adf4377.adf4377_init_param_f_clk_set)
    cp_i = property(_adf4377.adf4377_init_param_cp_i_get, _adf4377.adf4377_init_param_cp_i_set)
    muxout_select = property(_adf4377.adf4377_init_param_muxout_select_get, _adf4377.adf4377_init_param_muxout_select_set)
    ref_doubler_en = property(_adf4377.adf4377_init_param_ref_doubler_en_get, _adf4377.adf4377_init_param_ref_doubler_en_set)
    clkout_op = property(_adf4377.adf4377_init_param_clkout_op_get, _adf4377.adf4377_init_param_clkout_op_set)
    ref_div_factor = property(_adf4377.adf4377_init_param_ref_div_factor_get, _adf4377.adf4377_init_param_ref_div_factor_set)

    def __init__(self):
        _adf4377.adf4377_init_param_swiginit(self, _adf4377.new_adf4377_init_param())
    __swig_destroy__ = _adf4377.delete_adf4377_init_param

# Register adf4377_init_param in _adf4377:
_adf4377.adf4377_init_param_swigregister(adf4377_init_param)
cvar = _adf4377.cvar
linux_spi_ops = cvar.linux_spi_ops

class adf4377_dev(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    spi_desc = property(_adf4377.adf4377_dev_spi_desc_get, _adf4377.adf4377_dev_spi_desc_set)
    gpio_enclk1 = property(_adf4377.adf4377_dev_gpio_enclk1_get, _adf4377.adf4377_dev_gpio_enclk1_set)
    gpio_enclk2 = property(_adf4377.adf4377_dev_gpio_enclk2_get, _adf4377.adf4377_dev_gpio_enclk2_set)
    gpio_ce = property(_adf4377.adf4377_dev_gpio_ce_get, _adf4377.adf4377_dev_gpio_ce_set)
    dev_id = property(_adf4377.adf4377_dev_dev_id_get, _adf4377.adf4377_dev_dev_id_set)
    spi4wire = property(_adf4377.adf4377_dev_spi4wire_get, _adf4377.adf4377_dev_spi4wire_set)
    f_pfd = property(_adf4377.adf4377_dev_f_pfd_get, _adf4377.adf4377_dev_f_pfd_set)
    f_clk = property(_adf4377.adf4377_dev_f_clk_get, _adf4377.adf4377_dev_f_clk_set)
    f_vco = property(_adf4377.adf4377_dev_f_vco_get, _adf4377.adf4377_dev_f_vco_set)
    clkin_freq = property(_adf4377.adf4377_dev_clkin_freq_get, _adf4377.adf4377_dev_clkin_freq_set)
    cp_i = property(_adf4377.adf4377_dev_cp_i_get, _adf4377.adf4377_dev_cp_i_set)
    muxout_default = property(_adf4377.adf4377_dev_muxout_default_get, _adf4377.adf4377_dev_muxout_default_set)
    ref_doubler_en = property(_adf4377.adf4377_dev_ref_doubler_en_get, _adf4377.adf4377_dev_ref_doubler_en_set)
    ref_div_factor = property(_adf4377.adf4377_dev_ref_div_factor_get, _adf4377.adf4377_dev_ref_div_factor_set)
    clkout_div_sel = property(_adf4377.adf4377_dev_clkout_div_sel_get, _adf4377.adf4377_dev_clkout_div_sel_set)
    n_int = property(_adf4377.adf4377_dev_n_int_get, _adf4377.adf4377_dev_n_int_set)
    clkout_op = property(_adf4377.adf4377_dev_clkout_op_get, _adf4377.adf4377_dev_clkout_op_set)
    bleed_word = property(_adf4377.adf4377_dev_bleed_word_get, _adf4377.adf4377_dev_bleed_word_set)
    sr_del_adj = property(_adf4377.adf4377_dev_sr_del_adj_get, _adf4377.adf4377_dev_sr_del_adj_set)
    sr_inv = property(_adf4377.adf4377_dev_sr_inv_get, _adf4377.adf4377_dev_sr_inv_set)
    sysrefout = property(_adf4377.adf4377_dev_sysrefout_get, _adf4377.adf4377_dev_sysrefout_set)

    @staticmethod
    def init(param):
        return _adf4377.adf4377_dev_init(param)

    def __init__(self):
        _adf4377.adf4377_dev_swiginit(self, _adf4377.new_adf4377_dev())
    __swig_destroy__ = _adf4377.delete_adf4377_dev

# Register adf4377_dev in _adf4377:
_adf4377.adf4377_dev_swigregister(adf4377_dev)

def adf4377_spi_write(dev, reg_addr, data):
    return _adf4377.adf4377_spi_write(dev, reg_addr, data)

def adf4377_spi_update_bit(dev, reg_addr, mask, data):
    return _adf4377.adf4377_spi_update_bit(dev, reg_addr, mask, data)

def adf4377_spi_read(dev, reg_addr):
    return _adf4377.adf4377_spi_read(dev, reg_addr)

def adf4377_set_ref_clk(dev, val):
    return _adf4377.adf4377_set_ref_clk(dev, val)

def adf4377_get_ref_clk(dev, val):
    return _adf4377.adf4377_get_ref_clk(dev, val)

def adf4377_set_en_ref_doubler(dev, en):
    return _adf4377.adf4377_set_en_ref_doubler(dev, en)

def adf4377_get_en_ref_doubler(dev, en):
    return _adf4377.adf4377_get_en_ref_doubler(dev, en)

def adf4377_set_ref_div(dev, div):
    return _adf4377.adf4377_set_ref_div(dev, div)

def adf4377_get_ref_div(dev, div):
    return _adf4377.adf4377_get_ref_div(dev, div)

def adf4377_set_cp_i(dev, reg_val):
    return _adf4377.adf4377_set_cp_i(dev, reg_val)

def adf4377_get_cp_i(dev, reg_val):
    return _adf4377.adf4377_get_cp_i(dev, reg_val)

def adf4377_set_bleed_word(dev, word):
    return _adf4377.adf4377_set_bleed_word(dev, word)

def adf4377_get_bleed_word(dev, word):
    return _adf4377.adf4377_get_bleed_word(dev, word)

def adf4377_set_rfout(dev, val):
    return _adf4377.adf4377_set_rfout(dev, val)

def adf4377_get_rfout(dev, val):
    return _adf4377.adf4377_get_rfout(dev, val)

def adf4377_set_en_chan(dev, ch, en):
    return _adf4377.adf4377_set_en_chan(dev, ch, en)

def adf4377_get_en_chan(dev, ch, en):
    return _adf4377.adf4377_get_en_chan(dev, ch, en)

def adf4377_set_out_power(dev, ch, pwr):
    return _adf4377.adf4377_set_out_power(dev, ch, pwr)

def adf4377_get_out_power(dev, ch, pwr):
    return _adf4377.adf4377_get_out_power(dev, ch, pwr)

def adf4377_set_rfout_divider(dev, div):
    return _adf4377.adf4377_set_rfout_divider(dev, div)

def adf4377_get_rfout_divider(dev, div):
    return _adf4377.adf4377_get_rfout_divider(dev, div)

def adf4377_check_scratchpad(dev):
    return _adf4377.adf4377_check_scratchpad(dev)

def adf4377_set_sr_del_adj(dev, val):
    return _adf4377.adf4377_set_sr_del_adj(dev, val)

def adf4377_get_sr_del_adj(dev, val):
    return _adf4377.adf4377_get_sr_del_adj(dev, val)

def adf4377_set_en_sr_inv_adj(dev, en):
    return _adf4377.adf4377_set_en_sr_inv_adj(dev, en)

def adf4377_get_en_sr_inv_adj(dev, en):
    return _adf4377.adf4377_get_en_sr_inv_adj(dev, en)

def adf4377_set_en_sysref_monitor(dev, en):
    return _adf4377.adf4377_set_en_sysref_monitor(dev, en)

def adf4377_get_en_sysref_monitor(dev, en):
    return _adf4377.adf4377_get_en_sysref_monitor(dev, en)

def adf4377_set_ndel(dev, val):
    return _adf4377.adf4377_set_ndel(dev, val)

def adf4377_get_ndel(dev, val):
    return _adf4377.adf4377_get_ndel(dev, val)

def adf4377_set_rdel(dev, val):
    return _adf4377.adf4377_set_rdel(dev, val)

def adf4377_get_rdel(dev, val):
    return _adf4377.adf4377_get_rdel(dev, val)

def adf4377_set_freq(dev):
    return _adf4377.adf4377_set_freq(dev)

def adf4377_soft_reset(dev, spi_4wire):
    return _adf4377.adf4377_soft_reset(dev, spi_4wire)

def adf4377_init(device, init_param):
    return _adf4377.adf4377_init(device, init_param)

def adf4377_remove(dev):
    return _adf4377.adf4377_remove(dev)

def get_linux_spi_ops():
    return _adf4377.get_linux_spi_ops()

